USE [master]
GO

/****** Object:  Database [secInsight]    Script Date: 2020-01-20 10:22:54 ******/
CREATE DATABASE [secInsight]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'secInsight', FILENAME = N'E:\MSSQL\Data\secInsight.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'secInsight_log', FILENAME = N'E:\MSSQL\Data\secInsight_log.ldf' , SIZE = 11264KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [secInsight].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [secInsight] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [secInsight] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [secInsight] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [secInsight] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [secInsight] SET ARITHABORT OFF 
GO

ALTER DATABASE [secInsight] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [secInsight] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [secInsight] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [secInsight] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [secInsight] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [secInsight] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [secInsight] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [secInsight] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [secInsight] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [secInsight] SET  DISABLE_BROKER 
GO

ALTER DATABASE [secInsight] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [secInsight] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [secInsight] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [secInsight] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [secInsight] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [secInsight] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [secInsight] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [secInsight] SET RECOVERY FULL 
GO

ALTER DATABASE [secInsight] SET  MULTI_USER 
GO

ALTER DATABASE [secInsight] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [secInsight] SET DB_CHAINING OFF 
GO

ALTER DATABASE [secInsight] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [secInsight] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [secInsight] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [secInsight] SET  READ_WRITE 
GO


